
name: 部署文档

on:
  push:
    branches:
      # 确保这是你正在使用的分支名称
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CACTUSA_TOKEN }}
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          submodules: true

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true
          version: 8


      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm


      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          branch: gh-pages
          folder: src/.vuepress/dist
          token: ${{ secrets.CACTUSA_TOKEN }}

      - name: 复制到 Vercel
        if: always()
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.CACTUSA_TOKEN }}
          src_path: /.
          dst_path: /
          # 你的用户名
          dst_owner: cactus
          # 与 Vercel 链接的仓库名，也就是 Vercel 部署时新建的仓库
          dst_repo_name: Cactus
          dst_branch: main
          src_branch: gh-pages
          clean: true
